export const jobsData = [
  {
    id: 1,
    nombre: "Jhon Perez",
    identificacion: "12345",
    area: "Marketing y estrategias",
    cargo: "Director Creativo",
    rol: "Jefe",
    jefe: "Elisa Gómez",
  },
  {
    id: 2,
    nombre: "Jhon Perez",
    identificacion: "12345",
    area: "Marketing y estrategias",
    cargo: "Director Creativo",
    rol: "Jefe",
    jefe: "Elisa Gómez",
  },
  {
    id: 3,
    nombre: "Jhon Perez",
    identificacion: "12345",
    area: "Marketing y estrategias",
    cargo: "Director Creativo",
    rol: "Jefe",
    jefe: "Elisa Gómez",
  },
  {
    id: 4,
    nombre: "Jhon Perez",
    identificacion: "12345",
    area: "Marketing y estrategias",
    cargo: "Director Creativo",
    rol: "Jefe",
    jefe: "Elisa Gómez",
  },
  {
    id: 5,
    nombre: "Jhon Perez",
    identificacion: "12345",
    area: "Marketing y estrategias",
    cargo: "Director Creativo",
    rol: "Jefe",
    jefe: "Elisa Gómez",
  },
  {
    id: 6,
    nombre: "Jhon Perez",
    identificacion: "12345",
    area: "Marketing y estrategias",
    cargo: "Director Creativo",
    rol: "Jefe",
    jefe: "Elisa Gómez",
  },
];