export const employeesData = [
  {
    id: 1,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 2,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 3,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 4,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 5,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 6,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
];

/*
  {
    id: 7,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 8,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 9,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 10,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 11,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },
  {
    id: 12,
    nombre: "Juanita Gonzales Uribe",
    identificacion: "12345",
    direccion: "Dirección 1",
    telefono: "123-456-7890",
    ciudad: "Manizales",
    departamento: "Caldas",
  },

*/
